### ISSUE TITLE
Allow to download a zip file with selected data

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#172]
With a similar interface to Zenodo I would like to create a way to download all the files so that they can be published by the author themself on Zenodo if they want.

@kjappelbaum WDYT ?

**Comment by kjappelbaum** [comment]
We need to check a few things for that because the current filenames (with the `/`) which are quite useful for data mining and the visualizer cannot be easily created from the graphical interface on Zenodo. I had to use the API in the past to do that. 

But independent of that, it is probably good to have this functionality.

**Comment by lpatiny** [comment]
Should we directly upload the zip file in zenodo ?

**Comment by kjappelbaum** [comment]
i think you already implemented this, @lpatiny 

I think the upload of this file to zenodo is a separate issue (as you cannot have those nice folders if you upload single files using the UI)
