### ISSUE TITLE
implement filtering for mass deconvolution 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#285]
for the candidates it can be useful to have conditions similar to the polymer view.

**Comment by lpatiny** [comment]
It is already there
![image](https://user-images.githubusercontent.com/1484241/111196941-279fda00-85be-11eb-900d-d68064d602e5.png)

**Comment by lpatiny** [comment]
But the documentation is not there on the other hand ... I may ask the EPFL that is using it to write the documentation maybe.

**Comment by kjappelbaum** [comment]
yes :D #282 
i didn't look in the code but does it also allow constraints on the number of the MF parts?

**Comment by lpatiny** [comment]
You can search for the following values:

https://github.com/cheminfo/mass-tools/blob/185234c0c9a88d297f0fec999b32ae5a5d87dd61/packages/mf-generator/src/index.js#L59-L60

In order to search for MF parts the view has to be changed to an array of key / value. Up to now nobody asked for this feature but it should be relatively easy to add.

https://github.com/cheminfo/mass-tools/blob/185234c0c9a88d297f0fec999b32ae5a5d87dd61/packages/mf-generator/src/index.js#L50-L53
